name : Build the next app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  mybuild:
    name: My first build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Run next js build in the following
        uses: actions/setup-node@v2
        with:
            node-version: ${{matrix.node-version}}  
      - run: npm i
      - run: npm run build             